### ISSUE TITLE
How to speed up url collection from redis?

### ISSUE THREAD

**Issue by pythoncontrol** [rmax/scrapy-redis#103]
How to speed up url collection from redis? My scraper is often idle and it takes 10-30seconds before it reads urls from redis, why?

**Comment by pythoncontrol** [comment]
The answer is obviously REDIS_START_URLS_BATCH_SIZE

**Comment by rmax** [comment]
Fetching URLs in batches using the `MGET` command can increase the throughput (see  https://redis.io/commands/mget). I had a branch for this but haven't got time to finish it.
