### ISSUE TITLE
can scrapy-redis close the spider if received a sentinel now?

### ISSUE THREAD

**Issue by tarjintor** [rmax/scrapy-redis#106]
At first ,I thought SCHEDULER_IDLE_BEFORE_CLOSE is for the purpose that if the scheduler isn't received urls from the start_urls_queue in a certain time, the spider will  be closed,but after read the source code,it seems used for the timeout of pop from start_urls_queue, and I found a link from stackoverflow
https://stackoverflow.com/questions/43547562/scrapy-redis-stop-my-spiders-after-x-time-of-idle
it says so too,I also tried myself
So I changed the source code of scrapy-redis, and use a sentinel to stop the 'raise DontCloseSPider' line,and it seems work fine,but I am not sure if I am doing it correct,and whether scrapy-redis have it own way to stop a spider in a certain situation

**Comment by lovebaicai** [comment]
Hello, ```So I changed the source code of scrapy-redis, and use a sentinel to stop the 'raise DontCloseSPider' line,and it seems work fine,but I am not sure if I am doing it correct,and whether scrapy-redis have it own way to stop a spider in a certain situation```
How is this how is this operation? I have also encountered this problem. I did not close the way。
Thks！

**Comment by rmax** [comment]
No, there is no support for a custom sentinel. Feel free to make a PR.
