### ISSUE TITLE
The program does not close automatically？

### ISSUE THREAD

**Issue by lovebaicai** [rmax/scrapy-redis#107]
1. Scrapy-redis framework, redis stored xxx: requests have been crawled finished, but the program is still running, how to automatically stop the program, rather than has been running?

```
2017-08-07 09:17:06 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-08-07 09:18:06 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
```
2. Please help me.Ths!

**Comment by rmax** [comment]
The spider waits forever for new URLs. You can stop the process by sending the `SIGINT` signal or hitting `CTRL-C`.

Alternatively, you can customize this method https://github.com/rmax/scrapy-redis/blob/master/src/scrapy_redis/spiders.py#L83 to close the crawler when certain message is received (sentinel).

To close the crawler you can use `self.crawler.engine.close_spider(spider, 'finished')`

**Comment by lovebaicai** [comment]
@rmax 
Yes，I define:
```
if found == 0:
    self.crawler.engine.close_spider('queue is empty, the spider close ', spider.name)
```
Use the define code，Single crawler runing ok。
If use multiple processes to crawl，Not working。
Tks!

**Comment by rmax** [comment]
The correct syntax is:
```
    self.crawler.engine.close_spider(spider=self, reason='queue is empty, the spider close')
```

**Comment by lovebaicai** [comment]
Thank you very much!
