### ISSUE TITLE
Modify request

### ISSUE THREAD

**Issue by verzola** [rmax/scrapy-redis#110]
Is there any way to modify the request?

I am using Splash and I want to force a spider to use it, but for that I must use SplashResponse or scrapy.http.Response with meta['splash'] because of this validation:
```python
    def process_request(self, request, spider):
        if 'splash' not in request.meta:
            return
```
Is there any way to do something like this?
```python
from scrapy_redis.spiders import RedisSpider

class MySpider(RedisSpider):
    name = 'myspider'

    def _modify_request(self, url):
        return SplashRequest(url, this.parse)

    def parse(self, response):
        # do stuff
        pass
```

**Comment by rmax** [comment]
I think you can override the method ``make_request_from_data`` https://github.com/rmax/scrapy-redis/blob/master/src/scrapy_redis/spiders.py#L97

**Comment by verzola** [comment]
It worked just the way I wanted! Thank you very much!
