### ISSUE TITLE
Splash integration, which dedupe filter should I use?

### ISSUE THREAD

**Issue by verzola** [rmax/scrapy-redis#111]
Hi! I am using scrapy-redis together with [scrapy-splash](https://github.com/scrapy-plugins/scrapy-splash), and when setting them up, I saw that both define DUPEFILTER_CLASS. In this case which one should I keep?

```
# Ensure all spiders share same duplicates filter through redis.
DUPEFILTER_CLASS = "scrapy_redis.dupefilter.RFPDupeFilter"
```

```
# Set a custom DUPEFILTER_CLASS:
DUPEFILTER_CLASS = 'scrapy_splash.SplashAwareDupeFilter'
```

**Comment by acefei** [comment]
Try to customize your own RFPDupeFilter as below:
```
#-*-coding:utf-8-*-
from scrapy_redis.dupefilter import RFPDupeFilter
from scrapy_splash.dupefilter import splash_request_fingerprint

class MyRFPDupeFilter(RFPDupeFilter):
	def request_fingerprint(self, request):
		return splash_request_fingerprint(request)
```

**Comment by Sq-List** [comment]
Did you solve id?.
I am using scrapy-redis together with scrapy-splash too.

**Comment by bqlwx111** [comment]
The built-in de-weighting is based on the set of redis, so it is suggested to give redis official rebloom module implementation
