### ISSUE TITLE
How do I only receive url from redis?

### ISSUE THREAD

**Issue by MrTurtleW** [rmax/scrapy-redis#115]
I want to receive urls from redis, then I will crawl them myself after processing them, what should I do?

**Comment by chaseSpace** [comment]
add some configurtion to connect REDIS in your spider settings.like this:  
`'SCHEDULER_PERSIST':True,
        'DUPEFILTER_CLASS':'scrapy_redis.dupefilter.RFPDupeFilter',
        'SCHEDULER':'scrapy_redis.scheduler.Scheduler',
        'REDIS_HOST':'192.168.0.2',
        'REDIS_PORT':6379,
        'REDIS_START_URLS_AS_SET':True,
        'REDIS_START_URLS_KEY':'%(name)s:start_urls',`

**Comment by chaseSpace** [comment]
add some configurtion to connect REDIS in your spider settings.like this:  
`'SCHEDULER_PERSIST':True,  
        'DUPEFILTER_CLASS':'scrapy_redis.dupefilter.RFPDupeFilter',  
        'SCHEDULER':'scrapy_redis.scheduler.Scheduler',  
        'REDIS_HOST':'192.168.0.2',   
        'REDIS_PORT':6379,  
        'REDIS_START_URLS_AS_SET':True,  
        'REDIS_START_URLS_KEY':'%(name)s:start_urls',`

**Comment by chaseSpace** [comment]
if configuration is in settings.py,modify ":"  to "=",and remove the quotes of keys.
but i still recommend you to see a document or someone else's success case。
