### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by samwellzuk** [rmax/scrapy-redis#116]
There is a bug in scrapy-redis/src/scrapy_redis/scheduler.py :
```
def has_pending_requests(self):
    return len(self) > 0
```
Fix it:
```
def has_pending_requests(self):
    return len(self.queue) > 0
```

**Comment by rmax** [comment]
Do you get an error?

`len(self)` equals to `len(self.queue)`. See https://github.com/rmax/scrapy-redis/blob/master/src/scrapy_redis/scheduler.py#L79
