### ISSUE TITLE
No module named 'scapy_redis'

### ISSUE THREAD

**Issue by wildwind0** [rmax/scrapy-redis#117]
File "/home/wildwind/anaconda3/lib/python3.6/site-packages/scrapy/crawler.py", line 81, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
ModuleNotFoundError: No module named 'scapy_redis'

how can I solve this problem?

**Comment by rmax** [comment]
How did you installed the package?

**Comment by n0trace** [comment]
pip install scrapy-redis @wildwind0

**Comment by rmax** [comment]
There is a typo in `scapy_redis`, it should be `scrapy_redis`.

**Comment by YoungYQ2254** [comment]
The seam problem

**Comment by YoungYQ2254** [comment]
The same problem！
