### ISSUE TITLE
add a compress operation  after pickle Request ,is this a nice idea?

### ISSUE THREAD

**Issue by chaseSpace** [rmax/scrapy-redis#118]
I found the request object in the pickle push directly into the redis-server, but the pickle operation does not reduce the size of the request, although not encrypted by hash function of this irreversible, but whether through other compression algorithms to reduce the request size, and then enter the redis server in order to reduce the loss of memory?  
About reversible compression algorithm, I tried zlib, but I found that the compression ratio of request to pure string is very high, which reaches 10 times the compression ratio, but the compression ratio of request object is not high. Who has better compression algorithm recommendation? ^8^
**Wechat**: Mserath  
**Look forward to communicating with you~**

**Comment by rmax** [comment]
You could use a compression algorithm with a custom dictionary tailored for the data you are dealing with. Also you can try another serialization libraries like `msgpack` before compressing.

Another way to achieve better compression ratio  is to batch the requests but that requires accumulating them somehow in the scheduler (by size and time) before sending them to redis.

**Comment by chaseSpace** [comment]
Your response is too efficient,thanks first !  
I think I should try other serialization libraries 。
And i have another problem.Thank u very much again~...Now I am building a distributed crawler. I just started a crawler, and found that the request object numbers sent to redis did not increase to 100, and then began to decrease until 0. Where is the wrong configuration? My idea is that 1 crawlers are responsible for producing request to send to redis, crawler 2, 3.. Are responsible for obtaining request objects from redis and extracting items. That's code of cralwer 1:
`class YunqiSpider(CrawlSpider):
    name = 'yunqi'
    allowed_domains = ['yunqi.qq.com']
    start_urls = ['http://yunqi.qq.com/bk/so2/n30p1']

    rules = (
        Rule(LinkExtractor(allow=r'bk/so2/n30p\d+'), callback='parse_book_list', follow=True),
    )
    custom_settings = {
        'DOWNLOADER_MIDDLEWARES' : {
            'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware': None,
            'myScrapyPj.middlewares.FakeUserAgent': 100
            },

        'DOWNLOAD_DELAY':2,
        'COOKIES_ENABLED':False,

        'SCHEDULER_PERSIST':True,
        'DUPEFILTER_CLASS':'scrapy_redis.dupefilter.RFPDupeFilter',
        'SCHEDULER':'scrapy_redis.scheduler.Scheduler',
        'REDIS_HOST':'192.168.0.2',
        'REDIS_PORT':6379,
    
    }
    def parse_book_list(self, response):
        #解析列表页中的小说信息
        book_list = response.css('#detailedBookList .book')
        for book in book_list:
            book_url = book.css('a::attr("href")').extract_first()
            novelName = book.css('.book_info h3 > a::text').extract_first()
            novelId = book.css('.book_info h3 a::attr("id")').extract_first()
            novelAuthor = book.css('.book_info dl dd:nth-child(2) a::text').extract_first()
            novelType = book.css('.book_info dl dd:nth-child(4) a::text').extract_first()
            novelStatus = book.css('.book_info dl dd:nth-child(6)::text').extract_first()
            novelUpdateTime =book.xpath('div[@class="book_info"]/dl[2]/dd[1]/text()').extract_first()
            novelWords =book.xpath('div[@class="book_info"]/dl[2]/dd[2]/text()').extract_first()
            novelCoverUrl = book.css('a img::attr("src")').extract_first()
            i = yunqiItem(novelName=novelName,novelId=novelId,novelAuthor=novelAuthor,novelType=novelType,
                          novelStatus=novelStatus,novelUpdateTime=novelUpdateTime,novelWords=novelWords,
                          novelCoverUrl=novelCoverUrl)
            yield i
            #print(novelUpdateTime,novelWords,novelCoverUrl)
            if book_url:
                yield Request(book_url,meta={'novelId':novelId},callback=self.parse_book_detail)  #进入每本小说的详情页
    def parse_book_detail(self, response):
        #解析小说详情页中的小说信息
        if response.meta.get('comment'):

            _json_data = json.loads(response.body)
            isTrue = _json_data['status']
            if isTrue:
                novelCommentNum = _json_data.get('data').get('commentNum')
                #print(22222222222,novelCommentNum)
                _item_part = response.meta['i_list']
                i = yunqiDetailItem(novelId=_item_part[0],novelLabel=_item_part[1],novelAllClick=_item_part[2],
                                    novelAllPopular=_item_part[3],novelWeekPopular=_item_part[4],
                                    novelCommentNum=novelCommentNum)
                yield i
            else:
                print('not get comment!!!!')

        else:
            _novelId = response.meta['novelId']
            novelLabel = response.xpath('//div[@class="tags"]/text()').extract_first()
            novelAllClick = response.xpath('//div[@class="num"]/table//tr/td[1]/text()').extract_first()
            novelAllPopular = response.xpath('//div[@class="num"]/table//tr/td[2]/text()').extract_first()
            novelWeekPopular = response.xpath('//div[@class="num"]/table//tr/td[3]/text()').extract_first()

            # 从上面传递过来的"_novelId"字段值中提取出数字部分
            novelId = re.search('(\d+)',_novelId).group(1)
            # 生成列表保存字段用于后续传递
            item_list = [novelId, novelLabel, novelAllClick, novelAllPopular, novelWeekPopular]
            # 加上头部信息以获取json数据中的评论数量
            headers = {'Referer':"http://yunqi.qq.com/bk/xdyq/%s.html"% novelId }
            #拼接获取json数据的URL
            comment_JSurl = 'http://yunqi.qq.com/novelcomment/index.html?bid='+str(novelId)

            yield Request(comment_JSurl,callback=self.parse_book_detail,meta=
                                {'i_list':item_list,'comment':True},headers=headers)`

**Comment by rmax** [comment]
I'm not sure if I understand your problem. Could you provide more details?

**Comment by chaseSpace** [comment]
I've done it. ~

**Comment by grantstephens** [comment]
@chaseSpace would you mind sharing how you did it please.
