### ISSUE TITLE
Whether scrapy-redis can handle this situation - request urls have priority?

### ISSUE THREAD

**Issue by sunnypandas** [rmax/scrapy-redis#121]
Hi,

Whether scrapy-redis can handle this situation - request urls have priority? Such as I need a request  URL_1 to get the basic info and another request URL_2 to get the detail (URL_1 has to before URL_2)?

Thanks a lot.

**Comment by rmax** [comment]
It doesn't. You would need to implement a priority queue in redis as backend.

**Comment by sppsun** [comment]
Thank you @rmax  firstly.

This is really a problem in distributed system.
