### ISSUE TITLE
use txredisapi for asynchronous redis calls

### ISSUE THREAD

**Issue by cyruszhang** [rmax/scrapy-redis#124]
I was wondering whether this will provide some performance benefits. 

async DB calls definitely helps with scrapy performance. redis, being a memory backed storage, might not benefit as much; but synchronous redis calls with network hops still has performance degradation implications.

**Comment by rmax** [comment]
In some places we will not be able to perform async calls as the code expects synchronous execution. For example, `Scheduler.next_request` does not support deferreds right now: https://github.com/scrapy/scrapy/blob/2c5fa0c13051c6e963bc1f73ab4c52743efed50d/scrapy/core/engine.py#L149

**Comment by cyruszhang** [comment]
good point. redis interations here are:
enqueue, dequeue, dupefilter.request_seen
all seem to be necessarily synchronous

**Comment by cyruszhang** [comment]
what do you think of the dupefilter.request_seen part? does it support deferreds?
