### ISSUE TITLE
关于scrapy-redis是否支持传入多参数+多个url

### ISSUE THREAD

**Issue by d4wner** [rmax/scrapy-redis#125]
您好，我现在的需求是运行scrapy crawl test-scrapy，其中还会通过-a传入多个功能参数。
此外，我可能会通过list或者文本文档传入多个url，轮流爬取。
我想请问下scrapy-redis支持我的需求么？大概需要怎样操作呢？

我尝试过复用多线程/多进程，实在跟scrapy不适合，只有求助于第三方库了。

**Comment by d4wner** [comment]
By the way, could you tell me **how to add allow_domains dynamicly using scrapy-redis?**
I found the allow_domains list  could not be append easily.
The example code in the wild taught me to set allow_domains staticly.
eg：
```
self.allowed_domains = ['google.com']
```
But in fact, I need to fetch them from the redis-db one by one , I have not found a point to add allow_domains dynamicly.

**Comment by rmax** [comment]
You can set `allowed_domains = []` to disable the domains filtering and in your scraping code ensure you only follow the domains you want.

**Comment by LuckyPigeon** [comment]
Close this as a solve issue.
