### ISSUE TITLE
cannot connect remote redis database

### ISSUE THREAD

**Issue by youyiqin** [rmax/scrapy-redis#126]
error：
  File "/home/qyy/anaconda3/envs/weibo/lib/python3.5/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ReadOnlyError: You can't write against a read only slave.

I use REDIS_URL = 'redis://root:my_redis_password@ip:port'
But,I modify it： REDIS_URL = 'redis://localhost:port',it work...
I need to set a password for my remote database,so I want to use REDIS_URL.
What can I do?Thanks,My English is too bad..

**Comment by AYiXi** [comment]
这不是主从同步嘛, 不能写入从机, 链接主机写入?
