### ISSUE TITLE
How to set up REDIS_START_URLS_KEY to use POST request

### ISSUE THREAD

**Issue by hanwangkun** [rmax/scrapy-redis#130]
My project the first request is a post method request。I don't know how to solve it.

**Comment by sunshinean** [comment]
Who are you!

At 2018-09-13 14:07:25, "韩旺坤" <notifications@github.com> wrote:


My project the first request is a post method request。I don't know how to solve it.

**Comment by rmax** [comment]
You need to modify the code that retrieves the start urls from redis so that you can include the URL and the POST payload.

**Comment by LuckyPigeon** [comment]
Close this as a solve issue.
