### ISSUE TITLE
DUPEFILTER_CLASS  It doesn't work?

### ISSUE THREAD

**Issue by Canon88** [rmax/scrapy-redis#134]
hi, all: 
    I set DUPEFILTER_CLASS in the configuration file, but the xxx:dupefilter queue cannot be seen in Redis. It doesn't work?Can anyone tell me? Thank you very much!
   OS: Ubuntu 16.04
   Version: Scrapy 1.5.1
   Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

**Comment by Canon88** [comment]
How do I tell if DUPEFILTER_CLASS is working?

**Comment by Beaujor** [comment]
How do you solve this problem?
