### ISSUE TITLE
Update pipeline document

### ISSUE THREAD

**Issue by LuckyPigeon** [rmax/scrapy-redis#139]
In the quick start section, it seems forgot to mention the pipeline setting, and without the setting seems will cause yield item appear wrong result. Just like #137, please update the document, if need help, I can do the contribution as well.

**Comment by vinayak9303** [comment]
can you explain to me how to run this setup on windows, please I'm fresher now but I want to contribute to the open-source project.

**Comment by rmax** [comment]
@vinayak9303 I'm no windows user so I cannot help directly.

It would be nice if you can make it work somehow and document the steps, in case there is something difference needed for windows.

**Comment by LuckyPigeon** [comment]
@vinayak9303 
You can follow this note that I wrote
[Here](https://hackmd.io/h5MYGNLJTuCJmwuUr_d7SQ)
