### ISSUE TITLE
where method `make_requests_from_url` was defined?

### ISSUE THREAD

**Issue by Vickey-Wu** [rmax/scrapy-redis#150]
https://github.com/rmax/scrapy-redis/blob/31c022dd145654cb4ea1429f09852a82afa0a01c/src/scrapy_redis/spiders.py#L110

**Comment by JointEntropy** [comment]
Late answer)
It is defined in scrapy module itself. Look at `scrapy.spiders` source file and you will find `def make_requests_from_url(self, url)`.
And by now  it is deprecated by the way
