### ISSUE TITLE
Doc is bad.

### ISSUE THREAD

**Issue by BobDu** [rmax/scrapy-redis#151]
The docs site [https://scrapy-redis.readthedocs.io/en/stable/](https://scrapy-redis.readthedocs.io/en/stable/) is bad.

Who know how to fix it?  @rmax

**Comment by synodriver** [comment]
Any progress on this？

**Comment by rmax** [comment]
Probably will look into this next weekend 🙏🏽

**Comment by LuckyPigeon** [comment]
Here's our new version docs!
https://github.com/rmax/scrapy-redis/wiki
