### ISSUE TITLE
Multi-level url deduplication problem   多级url去重的问题

### ISSUE THREAD

**Issue by CWF-999** [rmax/scrapy-redis#155]
A website has tens of thousands or more urls after rendering, and these urls are hierarchical. If the url of the previous level is judged to be repeated, then its next level url is directly ignored. Can the problem scrapy_redis be solved? Where do I need to change?

一个网站经过渲染后有几万甚至更多url，这些url是分级的。如果上一级的url被判断重复了，那么它的下一级url就被直接忽略了，这个问题scrapy_redis能解决吗？我需要在哪里修改？有没有大佬能提供一个好的思路？

**Comment by leffss** [comment]
好问题，我也想知道答案

**Comment by nikan1996** [comment]
A possible solution：
Utilize `meta` data to see if the Request needs to be filtered.
`
r = Request(url,meta={"allow_duplicate":True})  # set  allow_duplicate True
`
Next step is to write your own RFPDupeFilter which is inherited from https://github.com/rmax/scrapy-redis/blob/31c022dd145654cb4ea1429f09852a82afa0a01c/src/scrapy_redis/dupefilter.py#L15 and rewrite `request_seen` function to handle the `allow_duplicate` value(return False or True).

**Comment by Zerorigin** [comment]
此类分级去重需要自己在代码的业务逻辑上进行处理， Scrapy Redis 的去重策略默认是按完整 URL 地址和 Headers 等其它 Payload 有效负载来做 Hash 指纹去重的。

**Comment by rmax** [comment]
@Zerorigin  is right.

You can extend the current mechanisms by:

* Passing URL along with `meta` values through the spider queue.
* Using more values in the fingerprinting so for a equivalent set of URLs, you just crawl the first one.

**Comment by LuckyPigeon** [comment]
Close this as solved.
