### ISSUE TITLE
捕获http 404、402、503..

### ISSUE THREAD

**Issue by wangtaihong** [rmax/scrapy-redis#158]
怎么捕获到http 404、402、503等？对于http错误 未爬取成功但是已经指纹记录，有啥方便的处理嘛？

**Comment by seal7** [comment]
应该有个响应的状态码吧 &nbsp;code &nbsp;之类的



---原始邮件---
发件人: "wangtaihong"<notifications@github.com&gt;
发送时间: 2019年11月30日(星期六) 晚上11:49
收件人: "rmax/scrapy-redis"<scrapy-redis@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [rmax/scrapy-redis] 捕获http 404、402、503.. (#158)



怎么捕获到http 404、402、503等？对于http错误 未爬取成功但是已经指纹记录，有啥方便的处理嘛？

**Comment by rmax** [comment]
> Translation: How to capture http 404, 402, 503, etc.? Is there any convenient way to handle http errors that are not crawled but have been fingerprinted?

What do you mean by capture?

IIRC, you could set [handle_httpstatus_all](https://docs.scrapy.org/en/latest/topics/spider-middleware.html#std:reqmeta-handle_httpstatus_all) flag.

**Comment by LuckyPigeon** [comment]
@wangtaihong 
Is this what you looking for?
```shell=python
from urllib.error import HTTPError
try:
    <do something>
except HTTPError as err:
    if err.code == 404:
       <whatever>
    else:
       raise
```

**Comment by nieweiming** [comment]
请求的meta里面加入  "handle_httpstatus_all": True

**Comment by LuckyPigeon** [comment]
Close this issue since it's solved
