### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BB-9E** [rmax/scrapy-redis#160]
I want to set the concurrency dynamically, such as 50 in the morning and 100 in the afternoon. May I have any good suggestions?

**Comment by rmax** [comment]
This is a general question not specific to `scrapy-redis`.

Basically you need a external supervisor to scale up or down according to your rules.

**Comment by BobDu** [comment]
@rmax I think this require can simple achieve use `DynamicCurrentRequestsExtensions` by me write.
@BB-9E It's OK?

```
import datetime
from scrapy.crawler import Crawler
from scrapy import signals


class DynamicCurrentRequestsExtensions:
    """Dynamic change current_requests num when morning or afternoon.

    @author: BobDu
    @email: i@bobdu.cc
    """

    def __init__(self, crawler: Crawler):
        self.crawler = crawler

        if not crawler.settings.getbool('DYNMAIC_CURRENT_REQUESTS_EXT_ENABLED'):
            raise NotConfigured

        self.morning_current_requests = crawler.settings.getint('MORNING_CURRENT_REQUESTS')
        self.afternoon_current_reuquests = crawler.settings.getint('AFTERNOON_CURRENT_REUQUESTS')

        self.crawler.signals.connect(self.request_scheduled, signals.request_scheduled)

    @classmethod
    def from_crawler(cls, crawler: Crawler):
        return cls(crawler)

    def request_scheduled(self, request, spider):
        if datetime.datetime.now().hour <= 12:
            current_requests = self.morning_current_requests
        else:
            current_requests = self.afternoon_current_reuquests

        self.crawler.engine.downloader.total_concurrency = current_requests

```

**Comment by BB-9E** [comment]
> @rmax I think this require can simple achieve use `DynamicCurrentRequestsExtensions` by me write.
> @BB-9E It's OK?
> 
> ```python
> import datetime
> from scrapy.crawler import Crawler
> from scrapy import signals
> 
> 
> class DynamicCurrentRequestsExtensions:
>     """Dynamic change current_requests num when morning or afternoon.
> 
>     @author: BobDu
>     @email: i@bobdu.cc
>     """
> 
>     def __init__(self, crawler: Crawler):
>         self.crawler = crawler
> 
>         if not crawler.settings.getbool('DYNMAIC_CURRENT_REQUESTS_EXT_ENABLED'):
>             raise NotConfigured
> 
>         self.morning_current_requests = crawler.settings.getint('MORNING_CURRENT_REQUESTS')
>         self.afternoon_current_reuquests = crawler.settings.getint('AFTERNOON_CURRENT_REUQUESTS')
> 
>         self.crawler.signals.connect(self.request_scheduled, signals.request_scheduled)
> 
>     @classmethod
>     def from_crawler(cls, crawler: Crawler):
>         return cls(crawler)
> 
>     def request_scheduled(self, request, spider):
>         if datetime.datetime.now().hour <= 12:
>             current_requests = self.morning_current_requests
>         else:
>             current_requests = self.afternoon_current_reuquests
> 
>         self.crawler.engine.downloader.total_concurrency = current_requests
> ```

**Comment by rmax** [comment]
Interesting solution. Can you generalize it to support time slices somehow?

Also this seems decoupled from scrapy-redis so it could be its own extension project.
