### ISSUE TITLE
Some redis key questions about queue with requests、dupefilter and start_urls.

### ISSUE THREAD

**Issue by Zerorigin** [rmax/scrapy-redis#161]
Project A and B will use the same dupefilter and requests queue when project A and B have the same spidername.
So how does scrapy-redis distinguish the queues for different project?
So it is necessary to add the project name to the redis key prefix?

I found these default settings:
https://github.com/rmax/scrapy-redis/blob/master/src/scrapy_redis/defaults.py

**Comment by rmax** [comment]
`scrapy-redis` assumes only one redis server. 

So, if you have only one redis server for different projects having same spider names, then yes, you need to use an appropriate prefix in the keys.

**Comment by Zerorigin** [comment]
> `scrapy-redis` assumes only one redis server.
> So, if you have only one redis server for different projects having same spider names, then yes, you need to use an appropriate prefix in the keys.

Thanks for reply my question.
This project is helpfull for me and thanks for your contribution.
