### ISSUE TITLE
scrapy-redis监听的redis_key是在需要哪个db里面lpush

### ISSUE THREAD

**Issue by 2424162** [rmax/scrapy-redis#163]
在哪个文件里定义了db位置

**Comment by ZYMAERMO** [comment]
in settings.py

**Comment by BobDu** [comment]
@2424162  default db is db 0 , no default settings file.

You can use like `REDIS_PARAMS={ 'db': 2}` .
/usr/local/lib/python3.8/site-packages/scrapy_redis/connection.py
```
    params = defaults.REDIS_PARAMS.copy()
    params.update(settings.getdict('REDIS_PARAMS'))
    # XXX: Deprecate REDIS_* settings.
    for source, dest in SETTINGS_PARAMS_MAP.items():
        val = settings.get(source)
        if val:
            params[dest] = val
```

**Comment by GeraldWu23** [comment]
> @2424162 default db is db 0 , no default settings file.
> 
> You can use like `REDIS_PARAMS={ 'db': 2}` .
> /usr/local/lib/python3.8/site-packages/scrapy_redis/connection.py
> 
> ```
>     params = defaults.REDIS_PARAMS.copy()
>     params.update(settings.getdict('REDIS_PARAMS'))
>     # XXX: Deprecate REDIS_* settings.
>     for source, dest in SETTINGS_PARAMS_MAP.items():
>         val = settings.get(source)
>         if val:
>             params[dest] = val
> ```
Will I overwrite other settings in REDIS_PARAMS if I just use like `REDIS_PARAMS={ 'db': 2}`?

**Comment by GeraldWu23** [comment]
@BobDu 
> @2424162 default db is db 0 , no default settings file.
> 
> You can use like `REDIS_PARAMS={ 'db': 2}` .
> /usr/local/lib/python3.8/site-packages/scrapy_redis/connection.py
> 
> ```
>     params = defaults.REDIS_PARAMS.copy()
>     params.update(settings.getdict('REDIS_PARAMS'))
>     # XXX: Deprecate REDIS_* settings.
>     for source, dest in SETTINGS_PARAMS_MAP.items():
>         val = settings.get(source)
>         if val:
>             params[dest] = val
> ```

Will I overwrite other settings if I do `REDIS_PARAMS={ 'db': 2}`?

**Comment by GeraldWu23** [comment]
@rmax thanks a lot, mate!

**Comment by LuckyPigeon** [comment]
Closed this as a solved issue
