### ISSUE TITLE
You ever used python 3.8 run this spider connection same redis server.

### ISSUE THREAD

**Issue by chenxuefeng346** [rmax/scrapy-redis#175]
You ever used python 3.8 run this spider connection same redis server.
Please delete redis key `spider_name:requests` in your redis.

_Originally posted by @BobDu in https://github.com/rmax/scrapy-redis/issues/170#issuecomment-653408567_

“Please delete redis key `spider_name:requests` in your redis.”
Can you explain it further？Thanks！

**Comment by BobDu** [comment]
scrapy 的 `Request` 请求对象  是通过pickle序列化后存在 redis里面存着的
python3.7和python3.8默认的pickle序列化协议版本不一致

**Comment by LuckyPigeon** [comment]
Closed this as a solved issue
