### ISSUE TITLE
 If a url fails, is it added to dupefilter? Or just is given up. 

### ISSUE THREAD

**Issue by Vincent-Xin** [rmax/scrapy-redis#177]
If I want to continue the spider, how would I get and retry the urls failed last time?

**Comment by qshine** [comment]
Request will be add filter set before initiate a network request. you should retry it in spider or middleware.

I hope it will help you.

**Comment by rpocase** [comment]
> Request will be add filter set before initiate a network request. you should retry it in spider or middleware.

Are there enough hooks in place to make requests in middleware to the configured redis scheduler? E.g., I have a use case where I know a request may fail (for throttling or some other reason) and I may decide to remove it from the dupefilter. Settings would give me access to the redis instance, but it would be nice to not have to bake in the redis queue name logic/communications inside the middleware to remove the request from dupefilter.

**Comment by LuckyPigeon** [comment]
Close this as a solved issue

**Comment by qshine** [comment]
> > Request will be add filter set before initiate a network request. you should retry it in spider or middleware.
> 
> Are there enough hooks in place to make requests in middleware to the configured redis scheduler? E.g., I have a use case where I know a request may fail (for throttling or some other reason) and I may decide to remove it from the dupefilter. Settings would give me access to the redis instance, but it would be nice to not have to bake in the redis queue name logic/communications inside the middleware to remove the request from dupefilter.

----
sorry there is no way to remove url from filter set at this time and it is not a good idea because may be have concurrent question
