### ISSUE TITLE
AttributeError: Can't pickle local object 'Crawler.__init__.<locals>.<lambda>'

### ISSUE THREAD

**Issue by ycq0125** [rmax/scrapy-redis#178]
![image](https://user-images.githubusercontent.com/49603999/98879303-30718980-24c0-11eb-8c2a-e7a42064f6b0.png)
What should I do about this? please help me！
在使用过程中发生以上错误，我想知道我该怎么做调试或者有直接的方法也行，谢谢

**Comment by rmax** [comment]
Which scrapy version are you using?

Are you using a `lambda` function as request callback in your code? This is not supported as `pickle` can't serialize `lambda` functions. 

(Maybe replacing `pickle` by `cloudpickle` might help in those cases)

**Comment by ycq0125** [comment]
scrapy:2.4.0
Maybe it's a conflict somewhere, when I didn't upgrade to 2.4.0, everything works properly，thank you.

**Comment by ycq0125** [comment]
this my problem.sorry

**Comment by narayananadi** [comment]
I need some more clarity on that, i an using scrapy 2.8.0 and having this issue

**Comment by rmax** [comment]
@narayananadi the log message above happens when you use lambda functions in your request callback. 

If you use a spider method it should be ok.
