### ISSUE TITLE
scrapy性能问题

### ISSUE THREAD

**Issue by ycq0125** [rmax/scrapy-redis#179]
您好，这是我的代码。
`class AmazonInfoSpider(RedisSpider):`
     ` name = 'amazon_info'`
    `# allowed_domains = ['amazon.com']`
    `# start_urls = [`
   ` #     'https://httpbin.org/ip',`
    `#     'https://httpbin.org/ip',`
   ` #     'https://httpbin.org/ip',`
   ` #     'https://httpbin.org/ip',`
    `#     'https://httpbin.org/ip',`
    `#     'https://httpbin.org/ip',`
   `#     'https://httpbin.org/ip',`
    `#     'https://httpbin.org/ip',`
    `#     'https://httpbin.org/ip',`
   ` #     'https://httpbin.org/ip',]`
    `custom_settings = {`
        `'REDIS_HOST': '127.0.0.1',`
       ` 'REDIS_PORT': 6379,`
        `'DUPEFILTER_CLASS': 'scrapy_redis.dupefilter.RFPDupeFilter',`
        `'SCHEDULER': "scrapy_redis.scheduler.Scheduler",`
        `'SCHEDULER_PERSIST': True,`
        `'SCHEDULER_QUEUE_CLASS': 'scrapy_redis.queue.PriorityQueue',`
        `'DOWNLOAD_DELAY': 5,`
       ` 'RANDOMIZE_DOWNLOAD_DELAY': True,`
        `'CONCURRENT_REQUESTS': 12,`
       ` 'DOWNLOAD_TIMEOUT': 40,`
       ` 'DOWNLOADER_MIDDLEWARES': {`
           ` # 'amazon.middlewares.AmazonHeadersMiddleware': 541,`
           ` # 'amazon.captchabuster.RobotMiddleware': 90,`
           ` 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware': None,`
        `}`
    `}`

    `# def make_requests_from_url(self, url):`
    `#     url = 'https://www.amazon.com/shops/A2T6YTQ54K16KZ?ref_=v_sp_storefront'`
    `#     return scrapy.Request(url, callback=self.parse, dont_filter=True)`

    `def parse(self, response, **kwargs):`
        `print('heihei', response.body)`
当我使用scrapy时len(engine.downloader.active)将是12，但是如果我采用scrapy-redis将会逐渐变小直到成为1。
![image](https://user-images.githubusercontent.com/49603999/99866108-8c878c80-2be9-11eb-94de-fe60f3e4e0fe.png)
这是使用scrapy-redis后的效果，
![image](https://user-images.githubusercontent.com/49603999/99866219-47178f00-2bea-11eb-9724-93ea2d8a8e52.png)
![image](https://user-images.githubusercontent.com/49603999/99866226-58f93200-2bea-11eb-81bf-46ec7c23c753.png)
所以我想请问有什么更好的方法提升效率吗？谢谢您！

_Originally posted by @ycq0125 in https://github.com/rmax/scrapy-redis/issues/43#issuecomment-731499768_

**Comment by qshine** [comment]
len(engine.downloader.active) 是正在被下载的数量, 所以最大应该为CONCURRENT_REQUESTS的数量, 然后会逐步减小

提升抓取效率可以考虑提高CONCURRENT_REQUESTS的值, 同时适当降低timeout的值

**Comment by LuckyPigeon** [comment]
closed this as a solved issue
