### ISSUE TITLE
Please release a new version based on master branch

### ISSUE THREAD

**Issue by Germey** [rmax/scrapy-redis#183]
Please release a new version based on master branch.

I'm developing a package based on Scrapy-Redis, but the newest release version is not same as the master branch.

For example, in scheduler.py:

```
self.df = load_object(self.dupefilter_cls).from_spider(spider)
```

The newest release version is not implemented as this, so I must change the source code and override it. But if based on master branch, it won't be changed.

Please release a new version based on master branch, thanks.

**Comment by Germey** [comment]
Also I'm glad to help maintaining this package, thanks~

**Comment by rmax** [comment]
hey @Germey, thanks for the initiative. I just invited you as collaborator.

The following days I can take a look at what is needed to streamline the process of releasing for collaborators. Meanwhile you can let me know what updates would make sense for you (i.e.: on top of my head, updating tests to run on py36-38 as well as docs).

**Comment by Germey** [comment]
@rmax Sorry for missing this reply, I find the invitation is expired. Count you please invite me again?

If you have more plans for the processing of releasing for collaborators, please let me know anytime. 

And I also want to add support for stat based on Redis, so all the stat are synced among all the spiders. Just like this issue https://github.com/rmax/scrapy-redis/issues/46 mentioned. Wonder if you think it is make sense for you.

**Comment by Germey** [comment]
@rmax Hey, for the feature I want to add which mentioned above, I send a PR https://github.com/rmax/scrapy-redis/pull/186, could you pls help review it?

**Comment by rmax** [comment]
Hey! Thanks for the stats collector, that's really cool feature. 

I will send you the collaborator invite tomorrow.

**Comment by Germey** [comment]
@rmax Thanks for your invitation, I've joined as a collaborator. BTW, do I have permission to publish a new release now? Do you need to add permission for me on PyPi? 

Also for my contribution yesterday, thanks for your merging. But there are a bug with redis 3.x, I've send another PR to fix a issue on redis 3.x, pls help to review it, thanks https://github.com/rmax/scrapy-redis/pull/187

**Comment by rmax** [comment]
Could you register to pypi.org and let me know your username?

**Comment by Germey** [comment]
My username is `Germey`, here is my home link of PyPi: https://pypi.org/user/Germey/

Thanks~

**Comment by rmax** [comment]
@Germey added you as maintainer on pypi 🚀

**Comment by Germey** [comment]
@rmax Thanks, I will try that and update if there are any problems.
