### ISSUE TITLE
WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by JQ-K** [rmax/scrapy-redis#192]
when run scrpay_redis   sometime  it  return  :3924
redis exceptions ResponseError: Command # 1 (ZRANGE xinghuoedu_spider:requests 0 0) of pipeline caused error WRONGTYPE Operation against a key holding the wrong kind of value

**Comment by rmax** [comment]
What version of the library and redis are you using?

**Comment by LuckyPigeon** [comment]
Close this issue for author not reply
