### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by milkeasd** [rmax/scrapy-redis#241]
I am using python 3.10. It prompt this error when scrapy-redis run. 
Any ideas ?

**Comment by milkeasd** [comment]
Problem solved. 
Change `from collections import Iterable` to `from collections.abc import Iterable` in the spiders.py

**Comment by LuckyPigeon** [comment]
This has already updated, please clone the latest version.
