### ISSUE TITLE
Scrapy 2.6.1 Unsupport function make_requests_from_url to use

### ISSUE THREAD

**Issue by ihandmine** [rmax/scrapy-redis#250]
I didn't find a way to use it instead, except to rewrite it

**Comment by careyuyu** [comment]
I had the same problem. I think its beacuse the version of this project on PyPI is too old. Try to get the newest version by git clone and it should solve the problem.

**Comment by LuckyPigeon** [comment]
@Germey Can you help update the pip version?

**Comment by zhajingwen** [comment]
object has no attribute 'make_requests_from_url'

**Comment by LuckyPigeon** [comment]
@zhajingwen `make_requests_from_url` has been deprecated from `scrapy`. Please clone from GitHub now, we will push a new version to pypi soon.

**Comment by LuckyPigeon** [comment]
@ihandmine @careyuyu @zhajingwen We released a new version just now, you can use `pip install scrapy-redis` to install `v0.7.3` now.
