### ISSUE TITLE
How to use scrapy-redis if I'm using start_requests() instead of start_urls in my spider?

### ISSUE THREAD

**Issue by ashwinbala99** [rmax/scrapy-redis#264]
For instance, my start_requests() takes other parameters in the form of a dictionary (refer to sample code)

```python
def start_requests(self):
        # load inputs from DB
        items = load_urls()

        for an item in items:            
            yield Request(
                url=item['URL],
                callback=self.parse,
                meta={
                    "someid": item["someid"],
                    "someinfo": item["someinfo"],
                },
            )
```

What should I do to incorporate scrapy-redis in my project?

**Comment by rmax** [comment]
See this method https://github.com/rmax/scrapy-redis/blob/master/src/scrapy_redis/spiders.py#L137

It already supports loading JSON data from redis as start urls.

I think you just need to push json-serialized data (`{"url": ..., "meta": {"someid": ...}}`) to the `<spidername>:start_urls` key in your redis instance.

**Comment by LuckyPigeon** [comment]
@ashwinbala99 
Just like @rmax said, just follow the [tutorial](https://github.com/rmax/scrapy-redis/wiki/Introduction), then you can send the requests with json-serialized data. Feel free to ask if you have any further questions :)

**Comment by ashwinbala99** [comment]
Hi,

Thank you for responding to my query promptly. I'll certainly reach out if
I have any more questions regarding the usage of the library.

Regards
Ashwin B
