### ISSUE TITLE
日志报警：String request is deprecated

### ISSUE THREAD

**Issue by maintain99** [rmax/scrapy-redis#265]
环境 ： Scrapy-redis 0.7.3， Scrapy 2.7.1， Python 3.10 
运行爬虫时日志报出警告：WARNING: String request is deprecated, please use JSON data format.
 Detail information, please check https://github.com/rmax/scrapy-redis#features
请问这个警告是什么意思，可以忽略它吗？

**Comment by wyphwl** [comment]
解决了吗
