### ISSUE TITLE
Cleanup requirements

### ISSUE THREAD

**Issue by devfox-se** [rmax/scrapy-redis#268]
Currently looking into the requirements that come along the package

https://github.com/rmax/scrapy-redis/blob/master/requirements.txt
```
scrapy>=2.0
redis>=4.0
six>=1.15
coverage
flake8
mock
pytest
tox
pytest-cov
```

these packages are completly uncecessary to perform the main package. I believe it is a good idea to get rid of them to not make the projects that rely on scrapy-redis filled with unnecessary packages

```
coverage
flake8
mock
pytest
tox
pytest-cov
```

**Comment by rmax** [comment]
You are right, there is a mix with requirements, ideally these should go to `requirements-test.txt`.
