### ISSUE TITLE
Is there a planned support for Python3.11?

### ISSUE THREAD

**Issue by lion137** [rmax/scrapy-redis#273]

**Comment by rmax** [comment]
Contributions are welcome!

**Comment by lion137** [comment]
I would be happy to get in (I'm maintaining a big scrapper with scrapy-redis), but I never did such a task before. Do you have some guidance how to proceeed?

**Comment by rmax** [comment]
First thing it would be to try to setup your project in Python 3.11.  

If everything installs fine then try to run it and see if you get the same behavior. 

If something goes wrong you can report back here and we can figure it out.

**Comment by lion137** [comment]
Coll, cool, cool, that was my plan, I just stopped seeing, that `scrapy-redis` supports ` =< 3.10`. I'm starting to create a new project then, and eventually will come back here.

**Comment by LuckyPigeon** [comment]
@rmax @lion137 
I've already built `scrapy_redis` with `python3.11`, it's compatible, I'll update the necessary files in these days.
