### ISSUE TITLE
Add Kafka Topic Integration to Scrapy Redis

### ISSUE THREAD

**Issue by hamed21q** [rmax/scrapy-redis#288]
I suggest adding a feature to Scrapy Redis for seamless integration with Kafka, enabling users to publish crawled items directly to a Kafka topic.
I'm willing to implement this feature and welcome feedback from the community. but this feature didn't exist in todos.rst so i opened this issue to ask if this feature is valuable for the maintainers or not.

best regurds

**Comment by rmax** [comment]
I'd suggest to create it as standalone library.
