### ISSUE TITLE
There is a compatibility issue with the latest scrapy-redis package of the new version of scrapy

### ISSUE THREAD

**Issue by georgeJzzz** [rmax/scrapy-redis#289]
I encountered a new problem。
Program error interrupt,  I am using scrapy==2.11.1, scrapy-redis==0.7.3
 
![image](https://github.com/rmax/scrapy-redis/assets/42543889/6fc23fea-9c4c-4bf3-a55d-4cc355dbc176)

In addition, since the latest package of scrapy-redis that is compatible with the new version of scrapy has not been released, need to package it 

I tried to package it myself and it works fine, is it possible to **update** the latest `scrapy-redis` **package**?   **_Very necessary_**

**thanks**

**Comment by Ehsan-U** [comment]
I'm also encountering the same problem

**Comment by Ehsan-U** [comment]
i'm not able to upgrade locally, how you did that? 
![image](https://github.com/rmax/scrapy-redis/assets/88642086/c7965885-c552-48a9-9ead-bf0e977030a4)

i'm using Ubuntu 22

**Comment by Ehsan-U** [comment]
![image](https://github.com/rmax/scrapy-redis/assets/88642086/e914a123-d5e0-416c-ae4e-fb687b5a1b6e)

there is no dist directory

**Comment by georgeJzzz** [comment]
My mistake,

you try ` python setup.py install`

**Comment by Ehsan-U** [comment]
Yes
`python setup.py install`

![image](https://github.com/rmax/scrapy-redis/assets/88642086/81bcfcf5-d9ba-467b-9b7b-22e43e3ae9c7)

i already installed zope-interface 6.2 installed on my system.

**Comment by shengchenyang** [comment]
> i already installed zope-interface 6.2 installed on my system.

@Ehsan-U It's not a `zope-interface` problem, it's `Twisted`. You need to `pip install Twisted==22.10.0` and then `python setup.py install` again.

Twisted version needs to be less than or equal to `22.10.0`.

This project can consider optimizing dependency management.

**Comment by Ehsan-U** [comment]
@shengchenyang Thanks, its upgraded successfully.

**Comment by VQHieu1012** [comment]
Hello @shengchenyang , how did you know the problem is Twisted? Can you share how you found out this?

**Comment by shengchenyang** [comment]
@VQHieu1012 Compatibility issues can be located through the `install_requires` parameter in setup.py, which is requirements.txt.Then you need to check step by step.

But I still recommend running `pip install wheel && make dist` in your python virtual environment. The binary package will be generated in the dist folder.Instead of using `python setup.py install`.

**Comment by VQHieu1012** [comment]
@shengchenyang  thanks for sharing.

**Comment by sify21** [comment]
I did this in `requirements.txt`, which seems ok
```
scrapy-redis @ git+https://github.com/rmax/scrapy-redis@48a7a8921ae064fe7b4202b130f1054ede9103d6
```
