### ISSUE TITLE
Scrapy-redis usage related issues 

### ISSUE THREAD

**Issue by Hao1617** [rmax/scrapy-redis#291]
# Description
Let me introduce my python program: First, I get the data I need to crawl from MySQL and then process the data into a URL through
![image](https://github.com/rmax/scrapy-redis/assets/56282383/6bf5420b-b8fc-48df-92b1-f1b0fa1d1b66)
Submit to redis and wait for crawling. If crawling fails, it will be resubmitted
![image](https://github.com/rmax/scrapy-redis/assets/56282383/d17377fe-8d8c-44a4-924a-ab5da394a338)
Successful data is stored in MySQL through the pipeline. Get data from MySQL to redis once a day.I can confirm that it only runs once a day.

After running, the amount of data stored in redis is abnormal.The data is larger than expected At present, it is found that it is caused by resubmitting the URL when crawling errors. How can I solve it?

**Comment by Hao1617** [comment]
![image](https://github.com/rmax/scrapy-redis/assets/56282383/98e556e4-c37c-46a1-80f1-3ee8758f18cd)

**Comment by Hao1617** [comment]
> ![image](https://private-user-images.githubusercontent.com/56282383/329170578-98e556e4-c37c-46a1-80f1-3ee8758f18cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDE2NzAsIm5iZiI6MTcxNTI0MTM3MCwicGF0aCI6Ii81NjI4MjM4My8zMjkxNzA1NzgtOThlNTU2ZTQtYzM3Yy00NmExLTgwZjEtM2VlODc1OGYxOGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA3NTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjAxYzhkM2VhMmNjMzljM2E3ZGU3MTVlZmNlYmE5OThhZTY2NmFmNzMxNWRjYTNlNTcyZGU3YjBiMjMyZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bu2Id2vRKSXtVuRritr1zmDsjfR-c9ZRgT0oBNognzg)



> ![图像](https://private-user-images.githubusercontent.com/56282383/329170578-98e556e4-c37c-46a1-80f1-3ee8758f18cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDE2NzAsIm5iZiI6MTcxNTI0MTM3MCwicGF0aCI6Ii81NjI4MjM4My8zMjkxNzA1NzgtOThlNTU2ZTQtYzM3Yy00NmExLTgwZjEtM2VlODc1OGYxOGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA3NTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjAxYzhkM2VhMmNjMzljM2E3ZGU3MTVlZmNlYmE5OThhZTY2NmFmNzMxNWRjYTNlNTcyZGU3YjBiMjMyZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bu2Id2vRKSXtVuRritr1zmDsjfR-c9ZRgT0oBNognzg)

50000

**Comment by Hao1617** [comment]
![image](https://github.com/rmax/scrapy-redis/assets/56282383/b41037ac-e8fe-40c4-88f5-1304b6155371)

**Comment by rmax** [comment]
Pass in the request meta the number of retry so that it doesn't retry indefinitely.

**Comment by Hao1617** [comment]
> Pass in the request meta the number of retry so that it doesn't retry indefinitely.

Does it mean that if the request fails, I don't need to add it again manually, the framework will automatically retry?

**Comment by Hao1617** [comment]
> Pass in the request meta the number of retry so that it doesn't retry indefinitely.

As shown.
![image](https://github.com/rmax/scrapy-redis/assets/56282383/637cfce1-f342-4170-b262-af1cad76f9ad)
This can be deleted

**Comment by Hao1617** [comment]
> Pass in the request meta the number of retry so that it doesn't retry indefinitely.

Under what circumstances will it retry

**Comment by Hao1617** [comment]
This is a problem with program logic. Please help me close this discussion.
