### ISSUE TITLE
Recommended redis configuration?

### ISSUE THREAD

**Issue by StaymanHou** [rmax/scrapy-redis#97]
After running for 4 hours, my redis took up 8G of memory and got stuck. And I had to restart it. Is there any recommended redis configuration for the scrapy redis use case in general?
In my case, I've got a 4cpu 16G machine, running 4 scrapy processes running with 32 concurrency.

**Comment by rolando** [comment]
It seems you are not consuming the messages fast enough. Could you monitor and share the size of the redis keys over time?

Also, are you sending items through redis? are you consuming them too?

**Comment by StaymanHou** [comment]
You are correct. It can't consume the message fast enough. I'd assume the job would take 1 week or so to finish with the machine I have. During the week, message would probably keep pilling up until the job is close to 90 or 95%. Most pages will generate 5 or 10 more pages to crawl. So basically the more it crawls the more items will be in the queue. It will stop generating more items in the queue only when it's about to finish the whole job.

**Comment by LuckyPigeon** [comment]
It will be nice if we have documentation guiding this issue.

**Comment by LuckyPigeon** [comment]
Please check out [this](https://github.com/rmax/scrapy-redis/wiki/Example-Usage-(Basic-Recommendation)) page.
